In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.08739417, 0.08176397, 0.11866649, 0.09276078, 0.10144104,
        0.05454678, 0.10953551, 0.08282174, 0.14442794, 0.12664166]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09871755, 0.09816331, 0.10185346, 0.09924876, 0.10011401,
        0.09552761, 0.10092767, 0.09826721, 0.10451144, 0.10266901]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.34834

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

ValueError: in user code:

    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\training.py", line 949, in compute_loss
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\losses.py", line 139, in __call__
        losses = call_fn(y_true, y_pred)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\losses.py", line 243, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\losses.py", line 1788, in categorical_crossentropy
        y_true, y_pred, from_logits=from_logits, axis=axis)
    File "D:\projects\demo\pytest\venv\.TF2\lib\site-packages\keras\backend.py", line 5119, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (32, 1) and (32, 10) are incompatible


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0701 - accuracy: 0.9782 - 660ms/epoch - 2ms/step


[0.07013282179832458, 0.9782000184059143]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test)

<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[1.5338415e-07, 2.9535679e-08, 1.3091632e-05, ..., 9.9981374e-01,
        7.8391366e-07, 3.6565416e-06],
       [1.2175850e-08, 5.5452924e-06, 9.9999118e-01, ..., 1.1440589e-13,
        4.5303963e-08, 3.5103916e-13],
       [1.2557007e-07, 9.9796104e-01, 2.1745978e-04, ..., 1.5723684e-03,
        1.9923343e-04, 3.0653264e-06],
       ...,
       [1.7038544e-11, 2.9754021e-10, 6.6763275e-11, ..., 8.2470746e-07,
        3.0722915e-06, 8.4877851e-05],
       [5.3765796e-09, 1.9181357e-09, 7.1433168e-12, ..., 1.7213284e-09,
        1.0216998e-04, 5.2047233e-09],
       [9.4746234e-08, 2.7069172e-10, 7.9603711e-07, ..., 2.1252444e-12,
        2.1498023e-10, 1.0134876e-11]], dtype=float32)>

In [16]:
model.save("mnist.h5")